### ISSUE TITLE
Use configs for configuration (instead of secrets)

### ISSUE THREAD

**Issue by alejandro-colomar** [secobau/nginx#4]
Secrets are for passwords and other sensitive data.

Configs are for configuration.  /etc/nginx/ is normal configuration for which configs should be used.

If some special /etc/nginx/conf.d/ file needs to be kept secret, it can be treated specially.

**Comment by alejandro-colomar** [comment]
[My fork](https://github.com/alejandro-colomar/nginx/) fixed this in 84f9de2

**Comment by scolomar** [comment]
> If some special /etc/nginx/conf.d/ file needs to be kept secret, it can be treated specially.

You treat it specially when using a secret to handle it. That is the purpose of secrets.

**Comment by alejandro-colomar** [comment]
But you shouldn't treat specially all files.  You should use configs for all the files, and then secrets for specific files.

**Comment by scolomar** [comment]
> But you shouldn't treat specially all files. You should use configs for all the files, and then secrets for specific files.

I understand your concern. Nevertheless your commit does not solve the issue but turns everything into configs and disables the use of secrets.

This image needs to be as generic as possible and you need to choose secrets or configs. Otherwise you would hardcode the image.

I have chosen secrets because they are safer than configs.

There is no particular reason to use configs over secrets. The only reason would be just of philosophical matter.

Secrets are not too expensive compared with configs in terms of resources. Instead they have much better performance. And obviously better security. That is why many customers choose to set up all their configurations as secrets without exception.

I would say the opposite of your statement: use secrets unless you have a good reason to use configs.

That reason could be that you do not have enough memory available.

**Comment by alejandro-colomar** [comment]
> > But you shouldn't treat specially all files. You should use configs for all the files, and then secrets for specific files.
> 
> I understand your concern. Nevertheless your commit does not solve the issue but turns everything into configs and disables the use of secrets.

They are not disabled.  You can still add secrets: `ln -sT /run/secrets/etc/nginx/conf.d/some-secret.conf /etc/nginx/conf.d/some-secret.conf`.  But everything that is not specifically treated as a secret will be treated as a config.

> 
> This image needs to be as generic as possible and you need to choose secrets or configs. Otherwise you would hardcode the image.
> 
> I have chosen secrets because they are safer than configs.
> 
> There is no particular reason to use configs over secrets. The only reason would be just of philosophical matter.

It is a very important one.

> 
> Secrets are not too expensive compared with configs in terms of resources. Instead they have much better performance. And obviously better security. That is why many customers choose to set up all their configurations as secrets without exception.
> 
> I would say the opposite of your statement: use secrets unless you have a good reason to use configs.
> 
> That reason could be that you do not have enough memory available.
